# Generated by Django 4.0.3 on 2022-03-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateInput',
            new_name='ChooseDate',
        ),
    ]
