# Generated by Django 4.0.3 on 2022-03-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_rename_dateinput_choosedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChooseDate',
        ),
    ]
