# Generated by Django 4.0.3 on 2022-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0003_delete_choosedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
